03_wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.enter, name="entry"), # If "<str:title>" contain blank space characters in the URL, they will be replaced by "%20".
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("random", views.random_page, name="random"),
]

03_wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

03_wiki/encyclopedia/forms.py
from django import forms

class EntryForm(forms.Form):
    # If we don't set the "label" attribute, the variable name will display as <label> and its first character also be capitalized.
    # "required=True" means the "required" attribute of <input>.
    # A "widget" is Django's representation of an HTML input element. The widget handles the rendering of the HTML, 
    # and the extraction of data from a GET/POST dictionary that corresponds to the widget.
    # Widgets should not be confused with the form fields. Form fields deal with the logic of input validation 
    # and are used directly in templates. Widgets deal with rendering of HTML form input elements on the web page 
    # and extraction of raw submitted data.
    # Whenever you specify a field on a form, Django will use a default widget that is appropriate to the type of data that is to be displayed.
    # The default of "widget" is "TextInput" (i.e. <input>). Choose "Textarea" (i.e. <textarea>) to use multi-line text field.
    # Use the "attrs" argument to specify the attributes of the field for CSS styling.
    title = forms.CharField(label="", required=True,  widget=forms.TextInput(attrs={
        "style":"height: 35px; width: 800px;", "class":"form-control", "id":"title_create"
    }))
    content = forms.CharField(label="", required=True, widget=forms.Textarea(attrs={
        "style":"height: 250px; width: 800px;", "class":"form-control", "id":"content_create"
    }))

03_wiki/encyclopedia/views.py
from django.shortcuts import render

# Create your views here.
from markdown2 import markdown
from django.core.files.storage import default_storage
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
import random
from . import util
from .forms import EntryForm  # Separate the forms into another .py file. Import module from the file of the same directory by ".<file_name>".


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def enter(request, title):
    # Because "title" is from urls, if "title" contain blank space characters in the URL, they will be replaced "%20".
    # But when "title" is passed to the view functiotn, "%20" will be converted back into blank space characters.
    title = title.strip() # Remove the leading and trailing spaces of "title".
    content = util.get_entry(title)
    if content is None:
        return render(request, "encyclopedia/error.html", {
            "error_title": "No Entry Found",
            "error_message": f"404 Error: Entry for \"{title}\" not found"
        })
    else:
        return render(request, "encyclopedia/entry.html", {
            "entry_title": title, # URLs cannot contain spaces. URL encoding normally replaces a space with a plus ('+') sign or with a "%20".
                                  # Here spaces in "title" of the url will be replaced by "%20" when rendering the template.
            "content": markdown(content, safe_mode=True) # "markdown()" converts Markdown syntax into HTML.
                                                         # If you are using Markdown on a web system which will transform text provided by untrusted users, 
                                                         # "safe_mode=True" ensures that the user's HTML tags are either replaced, removed or escaped.
        })


def search(request):
    query = request.GET.get("q").strip()
    if query in util.list_entries():
        return redirect("wiki:entry", title=query)  # Here the space in "query" of the url will be replaced by "+".

    results = util.search_entry(query)
    if not results:      # Check if "results" is empty.
        return render(request, "encyclopedia/error.html", {
            "error_title": "No Results",
            "error_message": "No results were found. You can create a new entry for it."
        })
    else:
        return render(request, "encyclopedia/search.html", {
            "query": query,
            "entries": results
        })

def random_page(request): # Don't use "random" as the function (view) name, because we are using the "random" package.
    # "HttpResponseRedirect" only supports hard-coded urls, that's why we need "reverse".
    # You can use "args" in "reverse" to pass the parameters for urls.
    return HttpResponseRedirect(reverse("wiki:entry", args=[random.choice(util.list_entries())])) # Note that use "[]" for agrs.
    
    # We can also use the "redirect" function, there are two way to use it.
    # Pass the name of a view and optionally some positional or keyword arguments:
    # return redirect("wiki:entry", title=random.choice(util.list_entries())) 
    # Pass a hardcoded url to "redirect":
    # return redirect(reverse("wiki:entry", args=[random.choice(util.list_entries())])) 


def create(request):
    if request.method == "POST":
        create_form = EntryForm(request.POST)
        if create_form.is_valid():
            title = create_form.cleaned_data.get("title").strip()
            content = create_form.cleaned_data.get("content").strip()
            if title in util.list_entries():
                return render(request, "encyclopedia/error.html", {
                    "error_title": "Entry Creation Failed",
                    "error_message": "Entry already exists. Entry titles cannot be repeated."
                })

            util.save_entry(title, content)
            return redirect("wiki:entry", title=title)

        else:
            return render(request,  "encyclopedia/create.html", {
                "create_form": create_form
            })
    
    # print(EntryForm())  # You can print "EntryForm()" to see exactly what it is.
    return render(request, "encyclopedia/create.html", {
        "create_form": EntryForm()
    })


def edit(request, title):
    if request.method == "POST":
        if request.POST.get("delete"):
            filename = f"entries/{title}.md"
            default_storage.delete(filename)
            return redirect("wiki:index")

        edit_form = EntryForm(request.POST)
        if edit_form.is_valid():
            title = edit_form.cleaned_data.get("title").strip()
            content = edit_form.cleaned_data.get("content").strip()
            util.save_entry(title, content)
            return redirect("wiki:entry", title=title)
        else:
            return render(request, "encyclopedia/edit.html", {
                "edit_form": edit_form
            })
          
    return render(request, "encyclopedia/edit.html", {
        # Set initial values for the required fields by giving an initial data dictionary to "EntryForm".
        # Note that it should be a dictionary that maps the names of fields to their respective initial values. 
        "edit_form": EntryForm({"title": title, "content": util.get_entry(title)})
    })

03_wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}Create New Entry{% endblock %}

{% block body %}
<h1>New Entry</h1>

<form action="{% url 'wiki:create' %}" method="POST">
    {% csrf_token %}

    <div style="margin-bottom: 20px;">
        <!-- <label> represents a caption for an element (usually for <input>) in a user interface.
             If users difficulty click on very small regions (such as checkboxes), We can set the attribute "for" of <label> 
             to be the same as the "id" of <input>. So when you click the label, it will toggle the field (i.e. <input>).-->
        <label for="title_create"><h5>Title:</h5></label>
        {{ create_form.title }}
    </div>

    <div style="margin-bottom: 20px;">
        <label for="content_create"><h5>Create entry content using Markdown syntax:</h5></label>
        {{ create_form.content }}
    </div>
    
    <button class="btn btn-primary">Create</button>
</form>
{% endblock %}

03_wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}Edit Entry{% endblock %}

{% block body %}
<h1>Edit the entry: {{ edit_form.title.value }}</h1>

<form action="{% url 'wiki:edit' title=edit_form.title.value %}" method="POST">
    {% csrf_token %}
    <div style="margin-bottom: 20px;">
        <label for="title_create"><h5>Edit Title:</h5></label>
        {{ edit_form.title }}
    </div>

    <div style="margin-bottom: 20px;">
        <label for="content_create"><h5>Edit entry content using Markdown syntax:</h5></label>
        {{ edit_form.content }}
    </div>
    
    <button class="btn btn-primary">Edit</button>

    <a href="{% url 'wiki:edit' title=edit_form.title.value %}">
        <button name="delete" value="True" class="btn btn-danger">Delete</button>
    </a>
</form>

{% endblock %}

03_wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}{{ entry_title }}{% endblock %}

{% block body %}
<!-- Since Markdown allows users to write HTML tags, users can attack websites by inserting malicious code. 
     For example, users can insert JavaScript code to perform cross-site scripting (XSS) attacks, 
     or other malicious code to steal sensitive information.
     To prevent this security risk, Django provides a safe filter, which is used to mark a string as safe HTML. 
     We can use the safe filter by adding "|safe" after the variable name you're substituting to ensure that the generated HTML is safe. -->
<!-- Cross-site scripting (XSS) is a security exploit which allows an attacker to inject into a website malicious client-side code. 
     This code is executed by the victims and lets the attackers bypass access controls and impersonate users. -->
{{ content|safe }}

<a href="{% url 'wiki:edit' title=entry_title %}"><button class="btn btn-primary">Edit</button></a>
 <!-- Note that "title" is the variable in the url (whose name is 'wiki:edit'),
      and if "entry_title" contains spaces, they will be replaced by "%20". -->

{% endblock %}

03_wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}{{ error_title }}{% endblock %}

{% block body %}
<h1>{{ error_message }}</h1>
{% endblock %}

03_wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

03_wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

03_wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}Search Results{% endblock %}

{% block body %}
    <h1>No results found for "{{ query }}".</h1>
    <h2>You may mean the results containing "{{ query }}":</h2>
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}