airline/flights/urls.py
from django.urls import path

from . import views

app_name = "flight"

urlpatterns = [
    path("", views.index, name="index"), # Note that it's normal to get an error at the root URL, because we haven't set it yet.
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book")
]

airline/flights/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Flight, Airport, Passenger

def index(request):
    return render(request, "flights/index.html", {
        "flights": Flight.objects.all()
    })


def flight(request, flight_id):
    flight = Flight.objects.get(pk=flight_id) # In most cases, the "pk" (primary key) argument can also be replaced with "id", because id is the primary key in most cases.
    return render(request, "flights/flight.html", {
        "flight": flight,
        "passengers": flight.passengers.all(),  # Note that "passengers" is the "related_name" argument which be used to track the passengers who happened to be on that flight.
        "non_passengers": Passenger.objects.exclude(flights=flight).all()   # Use "exclude()" to exclude certain objects from a query. 
                                                                            # Here is to exclude the passenger objects which have corresponded to this flight object,
                                                                            # i.e., exclude the passengers who are already on this flight.
    })


def book(request, flight_id):
    if request.method == "POST":
        # There is definitely some error checking that we should be doing here. 
        # But for simplicity, let's just assume for now that we're able to get a flight and get a passenger.
        flight = Flight.objects.get(pk=flight_id)           # Accessing the flight.
        passenger_id = int(request.POST["passenger"])       # Finding the passenger id from the submitted form data.
        passenger = Passenger.objects.get(pk=passenger_id)  # Finding the passenger based on the id.
        passenger.flights.add(flight)                       # Add passenger to the flight using ".add()",
                                                            # i.e., make this passenger object correspond to this flight oject.

        # return HttpResponseRedirect(reverse("flight:flight", args=[flight.id]))
        return redirect("flight:flight", flight_id=flight.id) 

airline/flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flight {{ flight.id }}</h1>
    <ul>
        <li>Origin: {{ flight.origin }}</li>
        <li>Destination: {{ flight.destination }}</li>
        <li>Duration: {{ flight.duration }} minutes</li>
    </ul>

    <h2>Passengers:</h2>
    <ul>
        {% for passenger in passengers %}
            <li>{{ passenger }}</li>
        {% empty %}
            <li>No Passengers.</li>
        {% endfor %}
    </ul>

    <h2>Add Passenger</h2>
    <!-- Generally speaking, anytime you want to manipulate the state of something, 
         especially manipulating the database, that should be inside of a "POST" request. -->
    <form action="{% url 'flight:book' flight_id=flight.id %}" method="post">
        {% csrf_token %}
        <select name="passenger" id="">
            {% for passenger in non_passengers %}
                <option value="{{ passenger.id }}">{{ passenger }}</option>
            {% endfor %}
        </select>
        <input type="submit">
    </form>

    <a href="{% url 'flight:index' %}">All Flights</a>
{% endblock %}

airline/flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flights:</h1>
    <ul>
        {% for flight in flights %}
            <li>
                <a href="{% url 'flight:flight' flight_id=flight.id %}">Flight {{ flight.id }}</a>: {{ flight.origin }} to {{ flight.destination }}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

airline/flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Flights</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>