02_django_example/django_example/urls.py
# urls.py contains directions for where users should be routed after navigating to a certain URL or what URLs I can access.
from django.contrib import admin
from django.urls import path, include

# "urlpatterns" is a list of all of the allowable URLs that can be accessed for the particular app.
urlpatterns = [
    path('admin/', admin.site.urls), # A path is already given to us by default called admin, it runs a default Django application called the admin application.

    # In this urls.py, we want to be able to include all of the paths from the urls.py within the application using
    # "include("<APP_NAME>.urls")", rather than adding a function from views.py to the second argument like we do in the urls.py of each app.
    # The first following line means to tell Django to look at the urls.py inside of the "hello" directory to figure out what additional URLs I can get to from there.
    # So this is one master urls.py file that might connect to multiple different other URL configurations that exist as well. 
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
    # Because we don't set "path('', include("<APP_NAME>.urls"))" for the root URL, 
    # you will encounter the 404 page at the homepage (localhost:8000).
]

02_django_example/hello/urls.py
# Django has one "urls.py "file that works for the entire project. But typically we'll have each app contain its own "urls.py" files. 
# So we can have each of those individual apps have its own "urls.py" file to control what URLs are available for that particular app. 

from django.urls import path 
from . import views # "from ." means from the current directory.

 # "urlpatterns" is a list of all of the allowable URLs that can be accessed for the particular app.
urlpatterns = [
    # The "path" function is the path converter
    # "path" gives us the ability to reroute URLs and has two or three arguments: 
    # 1. A string representing the URL path (here is the empty string which means nothing at the end of the route), 
    # 2. A function from "views.py" that we wish to call when this URL is visited. 
    #    That is, what view should be rendered when this URL is visited. 
    # 3. A name for that path or URL. This argument is optional. 
    #    Giving the name of the view to a particular URL pattern makes it easy to reference it from other parts of the app.
    # So if I want to render my "index" view (the "index" function in "views.py"). 
    # Then what I want to render when someone visits this URL (the empty URL) is going to be views.index. 
    path("", views.index, name="index"),           # Add "/hello" to the url of the home page to see the result.
                                                   # When you go to the root URL (homepage), you will encounter 404,
                                                   # because we don't set "path('', include("<APP_NAME>.urls"))" for the root URL 
    
    path("hey/david", views.david, name="david"), # Add "/hello/hey/david" to the url of the home page to see the result.

    # Use angle brackets "<>" to capture the values from the URL and pass them to the second arugment as the parameter to this function.
    # "str" inside of "<>" specify the type of the captured value "name".
    # If the type isn't specifed, the captured value type will be string by default. 
    # Note that the captured value must be named as the parameter of the called function so as to pass it to that funciton in views.py.
    # So here means that we capture the value "name" from the URL and convert it to a string, then this value is passed to the "greet" function in views.py as its parameter "name"
    path("<str:name>", views.greet, name="greet"), # Add "/hello/<name>" to the url of the home page to see the result, where "<name>" you can type anything you want.
]

02_django_example/tasks/urls.py
from django.urls import path
from . import views

# We have a few routes named "index" throughout our different apps, 
# so declare a variable named "app_name" (necessary) to prevent Django getting confused.
app_name = "tasks" 

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

02_django_example/tasks/views.py
# Django tends to store data inside of tables in the databases. 
# If table hasn't been created, we need to create it by running the command "python3 manage.py migrate" in the terminal. 
# This command will allow us to create all of the default tables inside of Django's database. 
from django import forms
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect

# Django provides an even easier way to collect information from a user: Django Forms.
# Now, we can create a new form within views.py by creating a Python class.
class NewTaskForm(forms.Form):
    # Inside of this class, I need to define all of the fields I would like for this form to have, 
    # all of the inputs that I would like the user to provide. 
    # So I want them to provide the name called "task" which will be a character field, or a "CharField", 
    # meaning I want the user to type in characters. Here I can give this a label, call it "New Task" which will display on the site.
    task = forms.CharField(label="New Task")

    # If we want to add new fields to the form, we can simply add them in views.py without typing additional HTML.
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)

    # Django automatically performs client-side validation, or validation local to the user's machine, 
    # meaning it will not allow a user to submit their form if it is incomplete.
    # You can try that if neither fields is not typed in or the "priority" field is not "min_value" ~ "max_value", the remainder will pop up.

def index(request):
    # We don't want to create the list "tasks" as a global variable and store the submitted data in it, 
    # so that all of the users who visit the page can see the exact same list.
    # We can employ a tool known as sessions to solve this problem 
    if "tasks" not in request.session:  # Check if there already exists a "tasks" key in our session, oththerwise create one.
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    # Django provides simple server-side validation, or validation that occurs once form data has reached the server.
    if request.method == "POST":

        # If I just use NewTaskForm without arguments, that will create a empty form.
        # If the argument is "request.POST" which contains all of the data that the user submitted when they submitted the form. 
        # So I create a form variable by taking all of that data and fill it into this new task form, which will contain now all of the data the user submitted.
        # That is, take in the data the user submitted and save it as form.
        form = NewTaskForm(request.POST)

        # Check if form data is valid (server-side). That is, are they providing all the necessary data in the right format.
        if form.is_valid():  
            
            # We can use ".cleaned_data["<key_name>"]" to access the submitted data whose key is called "task".
            # If the key doesn't exist, it will return KeyError.
            task = form.cleaned_data["task"] # Note that here we use square brackets "[]".
            # Also, we can use "cleaned_data.get("key_name")" to access the submitted data.
            # If the key doesn't exist, it will return None. So you can use this way if you are not sure whether the key exists.
            # task = form.cleaned_data.get("task") # Note that here we use parenthesis "()".

            # Add the new task to our list of tasks, and you can see it in the route "/tasks".
            request.session["tasks"] += [task] 

            # Return "HttpResponseRedirect" to redirect the user to a particular route, here is "/tasks", 
            # and see your submission of "New Task". Besides, we generally try not to hardcode URLs into our app.
            # The better design would be to give the name of the route and reverse engineer what the route actually is from that. 
            # So we can use the function called "reverse" with the argument "tasks:index" to find out 
            # what the exact URL of the "index" URL for the "tasks" is.
            return HttpResponseRedirect(reverse("tasks:index"))

        # If the form is valid, we take the data from the form, get the "task", save it inside the variable "tasks", and add it to the list "tasks".
        # Else if the form is not valid, we go ahead and render that same add.html file back to them.
        # But instead of providing a new form back to them, we will send back the existing form data back to them. 
        # So we can display information about any errors that might have come up.
        else:
            # If the form is invalid, re-render the page with existing information.
            return render(request, "tasks/add.html", {
                "form": form  # "form" displays error information.
            })
            # You can go to this page to fill out the "New Task" field and type a number between "min_value" and "max_value" in the "Priority" field.
            # Then change "min_value" or "max_value" in this file such that this number is not in the previous range, and go back to the page to submit. 
            # You will see an error occurs. That is why we generally want both client- and server-side validation. 
            # Because client-end version may be not the up-to-date, server-side should check again to avoid errors.

    # The default method is GET. That is, the user just tried to get the page rather than submit data to it, 
    # then we're just going to render to them an empty form. 
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()  # Create a empty form.
    })

02_django_example/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task:</h1>
    <form action="{% url 'tasks:add' %}" method="post"> <!-- Use {% csrf_token %} when method="post". -->

        <!-- Here the method of this form is "post", this means the form data is sensitive.
             So Django requires a token to prevent Cross-Site Request Forgery (CSRF) Attack. 
             This is an attack where a malicious user attempts to send a request to your server from somewhere other than your site. -->
        <!-- To solve this problem, when Django sends a response rendering a template, 
             it also provides a CSRF token that is unique with each new session on the site. 
             Then, when a request is submitted, Django checks to make sure the CSRF token associated with the request matches 
             one that it has recently provided. Therefore, if a malicious user on another site attempted to submit a request, 
             they would be blocked due to an invalid CSRF token. This CSRF validation is built into the Django Middleware framework, 
             which can intervene in the request-response processing of a Django app. -->
        <!-- Inside of settings.py in the "example" folder, we can see there's a whole bunch of middleware that's installed by default 
             inside of a Django app in terms of making sure that we have different features hooked into this request response processing. -->
        {% csrf_token %} <!-- In any template that uses a POST form, use the "csrf_token" tag inside the <form> element if the form is for an internal URL. -->
        <!-- This line adds a hidden input field with the CSRF token provided by Django.  
             So if we inspect this page's source code, we'll notice that a new input field has been added.
             and this input whose type is hidden, meaning we won't be able to see it normally, whose name is CSRF middleware token.
             We can see a long string of characters that Django has generated for us, such that when we submit this form, 
             it's going to check to make sure this token is valid. If it doesn't find this token, 
             it is not going to accept my form submission; if someone else goes to this website, 
             they are going to see a different token presented to them as well. 
             That helps to make sure that nobody can forge these sorts of requests. -->

        <!-- Plug in the variable "form" here. So Django will generate the necessary HTML to make that form work. -->
        {{ form }}  <!-- That's the same as "<input type="text" name="task">"." -->
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

02_django_example/tasks/templates/tasks/index.html
<!-- Like Jinja syntax, tell Django where this block should be inserted. -->
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks:</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
        <!-- If I run the "for" loop but it doesn't run at all because the sequence is empty, I can run the following part.
             Django provides this empty tag that just makes it easy to be able to deal with situations 
             where we're iterating over an empty list. -->
            <li>No tasks.</li>
        {% endfor %}
    </ul>
    <!--  Instead of hard-coding links though, we can use the name variable we assigned to each path in urls.py, 
          and create a link that looks. So if ever I were to change the route to something else, 
          Django would just figure out what the new URL should be. -->
    <!--  This could potentially create a problem though, because we may have a few routes named "index" throughout our different apps. 
          We can solve this by going into each of our app's urls.py file, and adding an <app_name> variable. 
          So we can use {# "{% url '<app_name>:<route_name>' %}" #} to tell Django where the path is. -->
    <a href="{% url 'tasks:add' %}">Add a New Task</a>
{% endblock %}

02_django_example/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Tasks</title>
</head>
<body>
    <!-- Like Jinja syntax, we can insert the other code from other HTML files to this HTML file. -->
    {% block body %}{% endblock %}
</body>
</html>